export const products = [
    {
        id: "1",
        title:"Feria",
        price: 200,
        stock: 5,
        imageURL:"https://res.cloudinary.com/dg3bhw03n/image/upload/v1729565651/DSC04331_lk1amo.jpg",
        desciption: "Una feria mexicana típica",
        brand: "abs_rta",
        category: "urbanas",
    },
    {
        id: "2",
        title:"Mercado",
        price: 250,
        stock: 6,
        imageURL:"https://res.cloudinary.com/dg3bhw03n/image/upload/v1729565658/DSC03917_ddvv0n.jpg",
        desciption: "Un mercado mexicano",
        brand: "abs_rta",
        category: "urbanas",
    },
    {
        id: "3",
        title:"Skate",
        price: 300,
        stock: 3,
        imageURL:"https://res.cloudinary.com/dg3bhw03n/image/upload/v1729565663/IMG_4425_cwley9.jpg",
        desciption: "Parque skater",
        brand: "abs_rta",
        category: "deporte",
    },
    {
        id: "4",
        title:"Duraznos",
        price: 150,
        stock: 2,
        imageURL:"https://res.cloudinary.com/dg3bhw03n/image/upload/v1729565659/_MG_3193_fyid90.jpg",
        desciption: "Textura de un durazno",
        brand: "abs_rta",
        category: "producto",
    },
    {
        id: "5",
        title:"Brujito",
        price: 400,
        stock: 8,
        imageURL:"https://res.cloudinary.com/dg3bhw03n/image/upload/v1729565655/_MG_6524_iomp9a.jpg",
        desciption: "Perrito de la calle",
        brand: "abs_rta",
        category: "animales",
    },
    {
        id: "6",
        title:"Loro",
        price: 500,
        stock: 9,
        imageURL:"https://res.cloudinary.com/dg3bhw03n/image/upload/v1729565665/IMG_8468_txw2a7.jpg",
        desciption: "Loro en el aviario de Polanco",
        brand: "abs_rta",
        category: "animales",
    },
]




